Repository Western-Health-Covid19-Collaboration/wh_covid19_app, pull requests merged in 2020-04, with the labels that each got.

#146 Add codeowners
  .github/CODEOWNERS
Labels: documentation

#145 Updates to the release notes to cover what we did today
  release-notes.txt
Labels: Documentation

#236 Feature - Firebase Analytics & Crashlytics
  android/app/build.gradle
  android/build.gradle
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/constants.dart
  lib/main.dart
  lib/utils/firebase.dart
  lib/view/airway/checklist/intubation_checklist_infographic_page.dart
  lib/view/airway/checklist/intubation_checklist_page.dart
  lib/view/airway/extubation/extubation_guidance_page.dart
  lib/view/airway/extubation/extubation_infographic_page.dart
  lib/view/airway/guidance/intubation_guidance_infographic_page.dart
  lib/view/airway/guidance/intubation_guidance_page.dart
  lib/view/disclaimer_view.dart
  lib/view/home_page.dart
  lib/view/icu_non_intensivist/daily_round/daily_round_view.dart
  lib/view/icu_non_intensivist/general_care_view.dart
  lib/view/icu_non_intensivist/tips_junior_staff_view.dart
  lib/view/icu_non_intensivist/ventilation/ventilation_infographic_page.dart
  lib/view/icu_non_intensivist/ventilation/ventilation_view.dart
  lib/view/info_view.dart
  lib/view/license_view.dart
  lib/view/ppe/ppe_off_guidance_method_1.dart
  lib/view/ppe/ppe_off_guidance_method_1_infographic.dart
  lib/view/ppe/ppe_off_guidance_method_2.dart
  lib/view/ppe/ppe_off_guidance_method_2_infographic.dart
  lib/view/ppe/ppe_on_guidance.dart
  lib/view/ppe/ppe_on_infographic_page.dart
  lib/view/ppe/ppe_view.dart
  lib/view/staff_welfare/your_welfare_view.dart
  pubspec.lock
  pubspec.yaml
Labels: Engineering, Enhancement

#270 Docs: Add info about stuck PRs and https with github
  CONTRIBUTING.md
Labels: Documentation
