Repository Western-Health-Covid19-Collaboration/wh_covid19_app, pull requests merged in 2020-03, with the labels that each got.

#65 add svg package & steps image assets dir
  pubspec.lock
  pubspec.yaml
Labels: #1 Priority

#64 Added main screen header SVG.
  assets/images/main_header.svg
Labels: #1 Priority

#66 Added more PPE donning and doffing steps and main screen logo
  assets/images/main_logo.svg
  assets/images/steps/off_goggles_2.png
  assets/images/steps/off_gownandgloves.png
Labels: #1 Priority

#54 Create ventilation screens for issue #28
  assets/text/icu_ventilation_adjuncts_content.html
  assets/text/icu_ventilation_initial_actions_content.html
  lib/hard_data.dart
  lib/main.dart
  lib/routes.dart
  lib/view/icu_non_intensivist/general_care_view.dart
  lib/view/icu_non_intensivist/tips_junior_staff_view.dart
  lib/view/icu_non_intensivist/ventilation/ventilation_view.dart
  lib/view/view_templates/html_text_card_view_template.dart
  pubspec.lock
  pubspec.yaml
Labels: #1 Priority

#68 Readme Updates
  README.md
Labels: documentation

#69 Create github101.md [skip ci]
  README.md
  docs/GITHUB101.md
  docs/create_new_issue.png
Labels: documentation

#90 Feature/readme updates v2
  Code-of-conduct.md
  README.md
Labels: documentation

#87 Steps to update release notes in PR template
  .github/PULL_REQUEST_TEMPLATE.md
  release-notes.txt
Labels: documentation

#82 Updated Home Screen Branding into WH Brand
  assets/images/main_header.svg
  lib/style.dart
  lib/utils/color.dart
  lib/view/home_page.dart
Labels: #1 Priority

#89 Feat/issue 32 ppe step by step guidance
  lib/main.dart
  lib/models/PPEStepInfo.dart
  lib/routes.dart
  lib/view/ppe/ppe_on_guidance.dart
  lib/view/ppe/ppe_view.dart
  lib/widget/cards/ppe_step_card.dart
  lib/widget/cards/reusable_card_base.dart
  lib/widget/reusable_card.dart
Labels: #1 Priority

#99 Screens for Taking PPE Off
  lib/hard_data.dart
  lib/main.dart
  lib/models/PPEStepInfo.dart
  lib/routes.dart
  lib/style.dart
  lib/view/ppe/ppe_off_guidance_method_1.dart
  lib/view/ppe/ppe_off_guidance_method_2.dart
  lib/view/ppe/ppe_on_guidance.dart
  lib/view/ppe/ppe_view.dart
  lib/widget/card_container.dart
  lib/widget/cards/ppe_step_card.dart
  lib/widget/notification_banner.dart
  lib/widget/ppe_card_container.dart
  pubspec.yaml
  release-notes.txt
Labels: #1 Priority

#107 Updates to readme
  README.md
  docs/Flow-Diagram.png
  docs/Main.png
Labels: #3 Priority

#127 Add in ADR's
  README.md
  docs/Architecture/ADR-0000 Template.md
  docs/Architecture/ADR-0001 Use Flutter.md
  docs/Architecture/ADR-0002 Embed content in the app.md
  docs/Architecture/ADR-0003 Use Flutter beta channel.md
Labels: documentation

#132 Update diagram and readme
  README.md
  docs/Flow-Diagram.png
  docs/Intubation - Checklist - 01 Team.png
  docs/Intubation - Guide - 01 Planning.png
  docs/Main.png
  docs/Yourself - PPE.png
Labels: documentation
